name: merge-pre-release

on:
  workflow_run:
    workflows: [build]
    types: [completed]
    branches: [master]

jobs:
  on-success:
    name: merge master --> pre-release
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: master
          target-branch: pre-release
