name: tag_release

on:
  pull_request:
    branches: [ release ]
    types: [ closed ]

jobs:
  tag-master:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Tag release
        uses: nionata/EzReleases@vX.X
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"