name: tag-release

on:
  pull_request:
    branches: [ release ]
    types: [ closed ]

jobs:
  tag-release:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch